settings:
  name: BlueXP cloud ops
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
  rss_page: "whats-new.html"
  release_notes_autogen:
    release_notes_repo: bluexp-relnotes

sidebar:
  entries:
    - title: BlueXP cloud ops docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about BlueXP cloud ops
          url: /concept-compute.html
        - title: Connect your AWS account
          url: /task-getting-started-compute.html
    - title: Analyze your compute costs
      url: /task-analyze-costs.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family
